from config.extensions import db
from models.collectorate import Collectorate

STANDARD_HOURS = "Mon–Wed: 8:30am–4:00pm | Thu–Fri: 8:30am–3:00pm"

COLLECTORATE_DATA = [
    {
        "code": "011", "name": "KINGSTON (KING STREET)",
        "parish": "KINGSTON",
        "address": "1-3 King Street, Kingston",
        "phone": "(876) 922-7919",
        "hours": STANDARD_HOURS,
        "lat": 17.9970, "lng": -76.7936,
    },
    {
        "code": "012", "name": "KINGSTON (STAMP OFFICE)",
        "parish": "KINGSTON",
        "address": "111 Harbour Street, Kingston",
        "phone": "(876) 922-6972",
        "hours": STANDARD_HOURS,
        "lat": 17.9954, "lng": -76.7890,
    },
    {
        "code": "021", "name": "ST. ANDREW (CONSTANT SPRING)",
        "parish": "ST. ANDREW",
        "address": "191 Constant Spring Road, Kingston 8",
        "phone": "(876) 969-0000",
        "hours": STANDARD_HOURS,
        "lat": 18.0267, "lng": -76.7834,
    },
    {
        "code": "022", "name": "ST. ANDREW (CROSS ROADS)",
        "parish": "ST. ANDREW",
        "address": "15B Old Hope Road, Kingston 6",
        "phone": "(876) 960-0097",
        "hours": STANDARD_HOURS,
        "lat": 18.0053, "lng": -76.7716,
    },
    {
        "code": "031", "name": "ST. THOMAS (MORANT BAY)",
        "parish": "ST. THOMAS",
        "address": "8 Church Street, Morant Bay",
        "phone": "(876) 982-2280",
        "hours": STANDARD_HOURS,
        "lat": 17.8808, "lng": -76.4091,
    },
    {
        "code": "032", "name": "ST. THOMAS (PORT MORANT)",
        "parish": "ST. THOMAS",
        "address": "Chapel Hill, Port Morant",
        "phone": "(876) 982-8213",
        "hours": STANDARD_HOURS,
        "lat": 17.8966, "lng": -76.3287,
    },
    {
        "code": "041", "name": "PORTLAND (PORT ANTONIO)",
        "parish": "PORTLAND",
        "address": "Fort George Street, Port Antonio",
        "phone": "(876) 993-2551",
        "hours": STANDARD_HOURS,
        "lat": 18.1742, "lng": -76.4516,
    },
    {
        "code": "042", "name": "PORTLAND (BUFF BAY)",
        "parish": "PORTLAND",
        "address": "Victoria Road, Buff Bay",
        "phone": "(876) 996-1479",
        "hours": STANDARD_HOURS,
        "lat": 18.1710, "lng": -76.6716,
    },
    {
        "code": "051", "name": "ST. MARY (ANNOTTO BAY)",
        "parish": "ST. MARY",
        "address": "Main Street, Annotto Bay",
        "phone": "(876) 996-2214",
        "hours": STANDARD_HOURS,
        "lat": 18.2696, "lng": -76.7650,
    },
    {
        "code": "052", "name": "ST. MARY (PORT MARIA)",
        "parish": "ST. MARY",
        "address": "Main Street, Port Maria",
        "phone": "(876) 994-2350",
        "hours": STANDARD_HOURS,
        "lat": 18.3694, "lng": -76.8883,
    },
    {
        "code": "061", "name": "ST. ANN (ST. ANN'S BAY)",
        "parish": "ST. ANN",
        "address": "5 Harbour Street, St. Ann's Bay",
        "phone": "(876) 972-1378",
        "hours": STANDARD_HOURS,
        "lat": 18.4349, "lng": -77.2002,
    },
    {
        "code": "062", "name": "ST. ANN (BROWN'S TOWN)",
        "parish": "ST. ANN",
        "address": "Main Street, Brown's Town",
        "phone": "(876) 975-2283",
        "hours": STANDARD_HOURS,
        "lat": 18.3971, "lng": -77.3571,
    },
    {
        "code": "063", "name": "ST. ANN (MONEAGUE)",
        "parish": "ST. ANN",
        "address": "Lot 14 Devon, Moneague",
        "phone": "(876) 973-0457",
        "hours": STANDARD_HOURS,
        "lat": 18.2979, "lng": -77.1189,
    },
    {
        "code": "071", "name": "TRELAWNY (FALMOUTH)",
        "parish": "TRELAWNY",
        "address": "Harbour Street, Falmouth",
        "phone": "(876) 954-3218",
        "hours": STANDARD_HOURS,
        "lat": 18.4975, "lng": -77.6554,
    },
    {
        "code": "072", "name": "TRELAWNY (JACKSON TOWN)",
        "parish": "TRELAWNY",
        "address": "Jackson Town, Trelawny",
        "phone": "(876) 610-4281",
        "hours": STANDARD_HOURS,
        "lat": 18.3690, "lng": -77.5126,
    },
    {
        "code": "081", "name": "ST. JAMES (MONTEGO BAY)",
        "parish": "ST. JAMES",
        "address": "18B Howard Cooke Boulevard, Montego Bay",
        "phone": "(876) 952-0000",
        "hours": STANDARD_HOURS,
        "lat": 18.4762, "lng": -77.9163,
    },
    {
        "code": "091", "name": "HANOVER (LUCEA)",
        "parish": "HANOVER",
        "address": "Church Street, Lucea",
        "phone": "(876) 956-2219",
        "hours": STANDARD_HOURS,
        "lat": 18.4512, "lng": -78.1735,
    },
    {
        "code": "101", "name": "WESTMORELAND (SAVANNA-LA-MAR)",
        "parish": "WESTMORELAND",
        "address": "Shops 5 & 9, Hendon Mall, Beckford Street, Savanna-la-Mar",
        "phone": "(876) 955-2557",
        "hours": STANDARD_HOURS,
        "lat": 18.2162, "lng": -78.1359,
    },
    {
        "code": "102", "name": "WESTMORELAND (DARLISTON)",
        "parish": "WESTMORELAND",
        "address": "Darliston District, Westmoreland",
        "phone": "(876) 955-0000",
        "hours": STANDARD_HOURS,
        "lat": 18.2654, "lng": -77.9988,
    },
    {
        "code": "111", "name": "ST. ELIZABETH (BLACK RIVER)",
        "parish": "ST. ELIZABETH",
        "address": "1-3 High Street, Black River",
        "phone": "(876) 965-2238",
        "hours": STANDARD_HOURS,
        "lat": 18.0258, "lng": -77.8477,
    },
    {
        "code": "112", "name": "ST. ELIZABETH (SANTA CRUZ)",
        "parish": "ST. ELIZABETH",
        "address": "Coke Drive, Santa Cruz",
        "phone": "(876) 966-2217",
        "hours": STANDARD_HOURS,
        "lat": 18.0548, "lng": -77.7244,
    },
    {
        "code": "121", "name": "MANCHESTER (MANDEVILLE)",
        "parish": "MANCHESTER",
        "address": "3 1/2 Caledonia Road, Mandeville",
        "phone": "(876) 962-3920",
        "hours": STANDARD_HOURS,
        "lat": 18.0416, "lng": -77.5042,
    },
    {
        "code": "122", "name": "MANCHESTER (CHRISTIANA)",
        "parish": "MANCHESTER",
        "address": "Main Street, Christiana",
        "phone": "(876) 964-2556",
        "hours": STANDARD_HOURS,
        "lat": 18.1769, "lng": -77.4666,
    },
    {
        "code": "131", "name": "CLARENDON (MAY PEN)",
        "parish": "CLARENDON",
        "address": "7 Windsor Avenue, May Pen",
        "phone": "(876) 786-0000",
        "hours": STANDARD_HOURS,
        "lat": 17.9666, "lng": -77.2429,
    },
    {
        "code": "132", "name": "CLARENDON (CHAPELTON)",
        "parish": "CLARENDON",
        "address": "Main Street, Chapelton",
        "phone": "(876) 987-2231",
        "hours": STANDARD_HOURS,
        "lat": 17.9071, "lng": -77.2752,
    },
    {
        "code": "133", "name": "CLARENDON (LIONEL TOWN)",
        "parish": "CLARENDON",
        "address": "Bustamante Drive, Lionel Town",
        "phone": "(876) 986-3237",
        "hours": STANDARD_HOURS,
        "lat": 17.8369, "lng": -77.1822,
    },
    {
        "code": "141", "name": "ST. CATHERINE (SPANISH TOWN)",
        "parish": "ST. CATHERINE",
        "address": "1 Twickenham Park, Spanish Town",
        "phone": "(876) 984-0000",
        "hours": STANDARD_HOURS,
        "lat": 17.9909, "lng": -76.9573,
    },
    {
        "code": "142", "name": "ST. CATHERINE (LINSTEAD)",
        "parish": "ST. CATHERINE",
        "address": "Rodney Hall Road, Linstead",
        "phone": "(876) 985-2286",
        "hours": STANDARD_HOURS,
        "lat": 18.1351, "lng": -77.0291,
    },
    {
        "code": "143", "name": "ST. CATHERINE (OLD HARBOUR)",
        "parish": "ST. CATHERINE",
        "address": "1 Vaz Drive, Old Harbour",
        "phone": "(876) 983-2284",
        "hours": STANDARD_HOURS,
        "lat": 17.9380, "lng": -77.1047,
    },
    {
        "code": "144", "name": "ST. CATHERINE (PORTMORE)",
        "parish": "ST. CATHERINE",
        "address": "Lot 8 Cookson Pen, Braeton Parkway, Portmore",
        "phone": "(876) 949-5696",
        "hours": "Mon–Sat: 8:30am–4:00pm",
        "lat": 17.9540, "lng": -76.8869,
    },
]


def seed_collectorates():
    with db.session.no_autoflush:
        for c in COLLECTORATE_DATA:
            if not Collectorate.query.filter_by(code=c["code"]).first():
                db.session.add(Collectorate(
                    code=c["code"],
                    name=c["name"],
                    full=f"{c['code']} {c['name']}",
                    parish=c["parish"],
                    address=c["address"],
                    phone=c["phone"],
                    hours=c["hours"],
                    lat=c["lat"],
                    lng=c["lng"],
                    is_active=True
                ))
    db.session.commit()
    print(f"✅ Seeded {len(COLLECTORATE_DATA)} collectorates.")