from .collectorate import Collectorate
from .user import User
from .role import Role
from .user_role import User_role
from .applicant_profile import Profile
from .officer_profile import OfficerProfile
from .supervisor_profile import SupervisorProfile
from .licence_record import LicenceRecord
from .application import Application
from .document import Document
from .application_event import ApplicationEvent
from .payment import Payment
from .face_verification import VerificationResult
from .digital_licence import DigitalLicence
from .ita_correspondence import ITACorrespondence